import type { MenuCategoryData } from "./menu-data"

export const trMenuData: MenuCategoryData[] = [
  {
    id: 2, // Kahvaltı
    name: "Kahvaltı",
    items: [
      {
        id: 1,
        name: "Serpme kahvaltı kişi başı",
        price: "650 TL",
        description:
          "Soğuk tabak, siyah ve kırmızı zeytin, 4 çeşit peynir tabak, ev yapımı reçel, fındık kreması, bal, kaymak, sigara böreği, sahanda yumurta, demlik çay.",
      },
      { id: 2, name: "Omelet", price: "300 TL" },
      { id: 3, name: "Omelet Sucuklu", price: "350 TL" },
      { id: 4, name: "Karışık Omelet", price: "350 TL" },
      { id: 5, name: "Kaşarlı Omelet", price: "300 TL" },
      { id: 6, name: "Kaşarlı Yumurta", price: "300 TL" },
      { id: 7, name: "Peynirli Sahanda Yumurta", price: "280 TL" },
      { id: 8, name: "Sahanda Yumurta (2 kişilik)", price: "300 TL" },
      { id: 9, name: "Sahanda Yumurta (4 kişilik)", price: "350 TL" },
      { id: 10, name: "Patatesli Yumurta", price: "300 TL" },
      { id: 11, name: "Sucuk (2 kişilik)", price: "300 TL" },
      { id: 12, name: "Sucuk (4 kişilik)", price: "400 TL" },
      { id: 13, name: "Sucuklu Yumurta (2 kişilik)", price: "350 TL" },
      { id: 14, name: "Sucuklu Yumurta (4 kişilik)", price: "450 TL" },
      { id: 15, name: "Yumurta Haşlama", price: "50 TL" },
      { id: 16, name: "Kızartma", price: "400 TL" },
      { id: 17, name: "Menemen (2 kişilik)", price: "300 TL" },
      { id: 18, name: "Menemen (4 kişilik)", price: "350 TL" },
      { id: 19, name: "Sigara Böreği", price: "280 TL" },
    ],
  },
  {
    id: 3, // Soğuk Başlangıçlar
    name: "Soğuk Başlangıçlar",
    items: [
      { id: 1, name: "Acılı", price: "290 TL" },
      { id: 2, name: "Atom", price: "290 TL" },
      { id: 3, name: "Biber Tarator", price: "290 TL" },
      { id: 4, name: "Borani", price: "280 TL" },
      { id: 5, name: "Brokoli", price: "290 TL" },
      { id: 6, name: "Çacık", price: "250 TL" },
      { id: 7, name: "Cennet Ezmesi", price: "280 TL" },
      { id: 8, name: "Çiğin Pilavı", price: "280 TL" },
      { id: 9, name: "Böğrülce", price: "280 TL" },
      { id: 10, name: "Ekşi Semiz", price: "280 TL" },
      { id: 11, name: "Enginar", price: "300 TL" },
      { id: 12, name: "Erik Meze", price: "200 TL" },
      { id: 13, name: "Fava", price: "200 TL" },
      { id: 14, name: "Haydari", price: "200 TL" },
      { id: 15, name: "Kırmızı Köz Biber", price: "200 TL" },
      { id: 16, name: "Kabak Girit", price: "200 TL" },
      { id: 17, name: "Kabak Şahin", price: "200 TL" },
      { id: 18, name: "Kaya Koruğu", price: "200 TL" },
      { id: 19, name: "Köpoğlu", price: "300 TL" },
      { id: 20, name: "Kuru Böğrülce", price: "150 TL" },
      { id: 21, name: "Manco", price: "200 TL" },
      { id: 22, name: "Mantar Ekşili", price: "200 TL" },
      { id: 23, name: "Pancar", price: "200 TL" },
      { id: 24, name: "Portakallı Patlıcan", price: "200 TL" },
      { id: 25, name: "Yoğurtlu Patlıcan", price: "200 TL" },
      { id: 26, name: "Kabak", price: "fiyat yok" },
      { id: 27, name: "Kabak Köz", price: "fiyat yok" },
      { id: 28, name: "Kırmızı Biber", price: "fiyat yok" },
      { id: 29, name: "Kuru", price: "fiyat yok" },
      { id: 30, name: "Mantar", price: "fiyat yok" },
      { id: 31, name: "Peynir Kavun", price: "400 TL" },
      { id: 32, name: "Peynir Şöğüş", price: "350 TL" },
      { id: 33, name: "Pilaki", price: "200 TL" },
      { id: 34, name: "Roka", price: "fiyat yok" },
      { id: 35, name: "Saksuka", price: "200 TL" },
      { id: 36, name: "Semiz Yoğurtlu", price: "200 TL" },
      { id: 37, name: "Şevketi Bostan", price: "200 TL" },
      { id: 38, name: "Topik", price: "200 TL" },
      { id: 39, name: "Turpotu", price: "200 TL" },
      { id: 40, name: "Yeşil Böğrülce", price: "200 TL" },
    ],
  },
  {
    id: 7, // Salatalar
    name: "Salatalar",
    items: [
      { id: 1, name: "Gavurdağ Kaşık Salata", price: "400 TL - 450 TL" },
      { id: 2, name: "Çoban Salatası", price: "350 TL - D. 200 TL" },
      { id: 3, name: "Peynirli Roka Salatası", price: "400 TL - 450 TL" },
      { id: 4, name: "Yeşil Salata", price: "350 TL - D. 200 TL" },
      { id: 5, name: "Karışık Salata", price: "350 TL" },
      { id: 6, name: "Peynirli Salata", price: "400 TL" },
      { id: 7, name: "Kaşık Salatası", price: "350 TL" },
    ],
  },
  {
    id: 4, // Sıcak Başlangıçlar
    name: "Sıcak Başlangıçlar",
    items: [
      { id: 1, name: "Mantar", price: "200 TL" },
      { id: 2, name: "Paçanga Böreği", price: "350 TL" },
      { id: 3, name: "Sigara Böreği", price: "280 TL" },
      { id: 4, name: "Kızartma Kd.", price: "350 TL" },
      { id: 5, name: "Kızartma Duble", price: "400 TL" },
      { id: 6, name: "Cips", price: "300 TL" },
      { id: 7, name: "Cips Duble", price: "350 TL" },
      { id: 8, name: "Sıcak Turpotu", price: "300 TL" },
      { id: 9, name: "Sıcak Patlıcan", price: "300 TL" },
    ],
  },
  {
    id: 12, // Deniz Ürünleri
    name: "Deniz Ürünleri",
    items: [
      { id: 1, name: "Ahtapot ve Çeşitleri", price: "850 TL - 950 TL" },
      { id: 2, name: "Karides ve Çeşitleri", price: "700 TL" },
      { id: 3, name: "Levrek Marin", price: "550 TL" },
      { id: 4, name: "Soslu Hamsi", price: "500 TL" },
      { id: 5, name: "Kalamar Tava / Izgara", price: "400 TL - 450 TL" },
      { id: 6, name: "Ahtapot Izgara / Güveç", price: "500 TL - 550 TL" },
      { id: 7, name: "Karides Izgara / Tava / Güveç", price: "750 TL - 800 TL - 850 TL" },
      { id: 8, name: "Levrek Cipsi", price: "900 TL" },
      { id: 9, name: "Okyanus Lokumu", price: "500 TL" },
      { id: 10, name: "Çipura (üreticim adet)", price: "fiyat yok" },
      { id: 11, name: "Çipura", price: "fiyat yok" },
      { id: 12, name: "Levrek", price: "fiyat yok" },
      { id: 13, name: "Barbun", price: "fiyat yok" },
      { id: 14, name: "Lahos", price: "fiyat yok" },
      { id: 15, name: "Sinarit", price: "fiyat yok" },
      { id: 16, name: "Mercan", price: "fiyat yok" },
      { id: 17, name: "Akya", price: "fiyat yok" },
    ],
  },
  {
    id: 5, // Ana Yemekler
    name: "Ana Yemekler",
    items: [
      { id: 1, name: "Köfte Izgara", price: "600 TL" },
      { id: 2, name: "Tavuk Izgara", price: "550 TL" },
      { id: 3, name: "Kuzu Şiş", price: "800 TL" },
      { id: 4, name: "Karışık Izgara", price: "950 TL" },
      { id: 5, name: "Kavurma", price: "850 TL" },
      { id: 6, name: "Tavuk Sote", price: "750 TL / 1.350 TL" },
      { id: 7, name: "Et Sote", price: "950 TL / 1.800 TL" },
    ],
  },
  {
    id: 11, // Tatlılar
    name: "Tatlılar",
    items: [
      { id: 1, name: "Ayva tatlısı", price: "300 TL" },
      { id: 2, name: "Kabak tatlısı", price: "300 TL" },
      { id: 3, name: "İncir tatlısı", price: "300 TL" },
      { id: 4, name: "Fırında helva", price: "450 TL" },
      { id: 5, name: "Katmer tatlısı", price: "450 TL" },
      { id: 6, name: "Meyve tabağı", price: "400 TL" },
      { id: 7, name: "Meyve tabağı (double)", price: "550 TL" },
      { id: 8, name: "Bal muz", price: "300 TL" },
      { id: 9, name: "Kaşık ayva", price: "300 TL" },
    ],
  },
  {
    id: 6, // İçecekler
    name: "İçecekler",
    items: [
      { id: 1, name: "Kola", price: "100 TL" },
      { id: 2, name: "Fanta", price: "100 TL" },
      { id: 3, name: "Gazoz", price: "100 TL" },
      { id: 4, name: "Ice tea ve çeşitleri", price: "120 TL" },
      { id: 5, name: "Meyve suları", price: "120 TL" },
      { id: 6, name: "Ayran", price: "80 TL" },
      { id: 7, name: "Soda", price: "80 TL" },
      { id: 8, name: "Soda Limon", price: "100 TL" },
      { id: 9, name: "Türk kahvesi", price: "80 TL - 120 TL" },
      { id: 10, name: "Nescafe", price: "150 TL" },
      { id: 11, name: "Bitki Çayı", price: "80 TL" },
      { id: 12, name: "Çay", price: "50 TL" },
      { id: 13, name: "Demlik Çay", price: "450 TL" },
      { id: 14, name: "Portakal suyu", price: "180 TL" },
      { id: 15, name: "Şalgam (küçük)", price: "100 TL" },
      { id: 16, name: "Şalgam Şişe", price: "180 TL" },
      { id: 17, name: "Su", price: "75 TL" },
      { id: 18, name: "Bira ve çeşitleri", price: "250 TL" },
    ],
  },
  {
    id: 14, // Rakı (Yeni Kategori)
    name: "Rakı",
    items: [
      { id: 1, name: "Efe Gold 20cl", price: "950 TL" },
      { id: 2, name: "Efe Gold 35cl", price: "1.200 TL" },
      { id: 3, name: "Efe Gold 50cl", price: "1.600 TL" },
      { id: 4, name: "Efe Gold 70cl", price: "2.150 TL" },
      { id: 5, name: "Efe Gold 100cl", price: "2.800 TL" },
      { id: 6, name: "Efe Yaş Üzüm 20cl", price: "700 TL" },
      { id: 7, name: "Efe Yaş Üzüm 35cl", price: "1.050 TL" },
      { id: 8, name: "Efe Yaş Üzüm 50cl", price: "1.450 TL" },
      { id: 9, name: "Efe Yaş Üzüm 70cl", price: "1.850 TL" },
      { id: 10, name: "Efe Yaş Üzüm 100cl", price: "2.500 TL" },
      { id: 11, name: "Efe Göbek Raki 20cl", price: "830 TL" },
      { id: 12, name: "Efe Göbek Raki 35cl", price: "1.200 TL" },
      { id: 13, name: "Efe Göbek Raki 50cl", price: "1.350 TL" },
      { id: 14, name: "Efe Göbek Raki 70cl", price: "2.350 TL" },
      { id: 15, name: "Efe Göbek Raki 100cl", price: "3.000 TL" },
      { id: 16, name: "Kara Efe Raki 20cl", price: "950 TL" },
      { id: 17, name: "Kara Efe Raki 35cl", price: "1.480 TL" },
      { id: 18, name: "Kara Efe Raki 70cl", price: "2.750 TL" },
      { id: 19, name: "Efe Gold Özel Seri 70cl", price: "fiyat yok" },
      { id: 20, name: "Yeni Raki 20cl", price: "850 TL" },
      { id: 21, name: "Yeni Raki 35cl", price: "1.050 TL" },
      { id: 22, name: "Yeni Raki 50cl", price: "1.400 TL" },
      { id: 23, name: "Yeni Raki 70cl", price: "1.800 TL" },
      { id: 24, name: "Yeni Raki 100cl", price: "2.400 TL" },
      { id: 25, name: "Ala Raki 20cl", price: "840 TL" },
      { id: 26, name: "Ala Raki 35cl", price: "1.450 TL" },
      { id: 27, name: "Ala Raki 70cl", price: "2.600 TL" },
      { id: 28, name: "Y.R Yeni Seri 20cl", price: "900 TL" },
      { id: 29, name: "Y.R Yeni Seri 35cl", price: "1.150 TL" },
      { id: 30, name: "Y.R Yeni Seri 70cl", price: "2.000 TL" },
      { id: 31, name: "Tekirdağ Raki 20cl", price: "800 TL" },
      { id: 32, name: "Tekirdağ Raki 35cl", price: "1.400 TL" },
      { id: 33, name: "Tekirdağ Raki 50cl", price: "1.550 TL" },
      { id: 34, name: "Tekirdağ Raki 70cl", price: "2.000 TL" },
      { id: 35, name: "Tekirdağ Gold 20cl", price: "800 TL" },
      { id: 36, name: "Tekirdağ Gold 35cl", price: "1.200 TL" },
      { id: 37, name: "Tekirdağ Gold 50cl", price: "1.700 TL" },
      { id: 38, name: "Tekirdağ Gold 70cl", price: "2.200 TL" },
      { id: 39, name: "Tekirdağ Gold 100cl", price: "2.900 TL" },
      { id: 40, name: "Raki (T)", price: "350 TL" },
      { id: 41, name: "Raki (D)", price: "450 TL" },
    ],
  },
  {
    id: 15, // Şaraplar (Yeni Kategori)
    name: "Şaraplar",
    items: [
      { id: 1, name: "V.Doluca (D)", price: "450 TL" },
      { id: 2, name: "V.Doluca 35cl", price: "350 TL" },
      { id: 3, name: "V.Doluca 70cl", price: "1.800 TL" },
      { id: 4, name: "Villa D. Neo 70cl", price: "fiyat yok" },
      { id: 5, name: "Villa D. Roze 70cl", price: "fiyat yok" },
      { id: 6, name: "Verano 70cl", price: "fiyat yok" },
      { id: 7, name: "Antik 70cl", price: "fiyat yok" },
      { id: 8, name: "Alçtepe Kirte 70cl", price: "fiyat yok" },
      { id: 9, name: "Çankaya 35cl", price: "fiyat yok" },
      { id: 10, name: "Çankaya 70cl", price: "fiyat yok" },
      { id: 11, name: "DLC Boğazkere 70cl", price: "fiyat yok" },
      { id: 12, name: "DLC Cab. Sauvignon Merlot 70cl", price: "fiyat yok" },
      { id: 13, name: "DLC Grenache 70cl", price: "fiyat yok" },
      { id: 14, name: "DLC Kalecik Karası 70cl", price: "fiyat yok" },
      { id: 15, name: "DLC Moskado (Dömişek) 70cl", price: "fiyat yok" },
      { id: 16, name: "DLC Narince 70cl", price: "fiyat yok" },
      { id: 17, name: "DLC Öküzgözü 70cl", price: "fiyat yok" },
      { id: 18, name: "DLC Ply 70cl", price: "fiyat yok" },
      { id: 19, name: "DLC Shiraz 70cl", price: "fiyat yok" },
      { id: 20, name: "DLC Sauvignon Blanc 70cl", price: "fiyat yok" },
      { id: 21, name: "DLC Sultaniiye Emir 70cl", price: "fiyat yok" },
      { id: 22, name: "Kav Narince 70cl", price: "fiyat yok" },
      { id: 23, name: "Terra Öküzgözü Boğazkere 70cl", price: "fiyat yok" },
      { id: 24, name: "Küp Beş Bir Yerden Beyaz 70cl", price: "fiyat yok" },
      { id: 25, name: "Küp Beş Bir Yerden Kırmızı 70cl", price: "fiyat yok" },
      { id: 26, name: "Küp Epic Chardonnay 70cl", price: "fiyat yok" },
      { id: 27, name: "Küp Epic Merlot 70cl", price: "fiyat yok" },
      { id: 28, name: "Küp Thia Blush 70cl", price: "fiyat yok" },
      { id: 29, name: "Küp Thia Cab. Sav. 70cl", price: "fiyat yok" },
      { id: 30, name: "Küp Thia Chardonnay 70cl", price: "fiyat yok" },
      { id: 31, name: "Küp Thia Merlot 70cl", price: "fiyat yok" },
      { id: 32, name: "Küp Sav Blanc 70cl", price: "fiyat yok" },
      { id: 33, name: "Leona Blush 70cl", price: "fiyat yok" },
      { id: 34, name: "Leona Buble 70cl", price: "fiyat yok" },
      { id: 35, name: "Leona Narince 70cl", price: "fiyat yok" },
      { id: 36, name: "Leona Shiraz 70cl", price: "fiyat yok" },
      { id: 37, name: "Sarafin Cab. Sauvignon 35cl", price: "fiyat yok" },
      { id: 38, name: "Sarafin Cab. Sauvignon 70cl", price: "fiyat yok" },
      { id: 39, name: "Sarafin Sauvignon Blanc 70cl", price: "fiyat yok" },
      { id: 40, name: "Sarafin Meritage 70cl", price: "fiyat yok" },
      { id: 41, name: "Sarafin Roze 70cl", price: "fiyat yok" },
      { id: 42, name: "Selection 70cl", price: "fiyat yok" },
      { id: 43, name: "Signum Beyaz 70cl", price: "fiyat yok" },
      { id: 44, name: "Signum Roze 70cl", price: "fiyat yok" },
      { id: 45, name: "Signum Kırmızı 70cl", price: "fiyat yok" },
    ],
  },
]
