import { trMenuData } from "./menu-data-tr" // Yeni Türkçe veriyi içe aktar

export interface MenuItem {
  id: number
  name: string
  description?: string
  price: string
  image?: string
}

export interface MenuCategoryData {
  id: number
  name: string
  items: MenuItem[]
}

// Diğer diller için yer tutucu veriler - bunlar benzer şekilde doldurulmalıdır
const enMenuData: MenuCategoryData[] = [
  {
    id: 2,
    name: "Breakfast",
    items: [
      {
        id: 1,
        name: "Spread Breakfast per person",
        price: "650 TL",
        description:
          "Cold plate, black and red olives, 4 types of cheese, homemade jam, hazelnut cream, honey, clotted cream, sigara böreği, fried egg, pot of tea.",
      },
      { id: 2, name: "Omelet", price: "300 TL" },
      { id: 3, name: "Omelet with Sucuk", price: "350 TL" },
      { id: 4, name: "Mixed Omelet", price: "350 TL" },
      { id: 5, name: "Cheese Omelet", price: "300 TL" },
      { id: 6, name: "Eggs with Cheese", price: "300 TL" },
      { id: 7, name: "Fried Eggs with Cheese", price: "280 TL" },
      { id: 8, name: "Fried Eggs (for 2)", price: "300 TL" },
      { id: 9, name: "Fried Eggs (for 4)", price: "350 TL" },
      { id: 10, name: "Eggs with Potatoes", price: "300 TL" },
      { id: 11, name: "Sucuk (for 2)", price: "300 TL" },
      { id: 12, name: "Sucuk (for 4)", price: "400 TL" },
      { id: 13, name: "Sucuk with Eggs (for 2)", price: "350 TL" },
      { id: 14, name: "Sucuk with Eggs (for 4)", price: "450 TL" },
      { id: 15, name: "Boiled Egg", price: "50 TL" },
      { id: 16, name: "Fried Potatoes", price: "400 TL" },
      { id: 17, name: "Menemen (for 2)", price: "300 TL" },
      { id: 18, name: "Menemen (for 4)", price: "350 TL" },
      { id: 19, name: "Sigara Böreği", price: "280 TL" },
    ],
  },
  {
    id: 3,
    name: "Cold Appetizers",
    items: [
      { id: 1, name: "Spicy Ezme", price: "290 TL" },
      { id: 2, name: "Atom", price: "290 TL" },
      { id: 3, name: "Pepper Tarator", price: "290 TL" },
      { id: 4, name: "Borani", price: "280 TL" },
      { id: 5, name: "Broccoli", price: "290 TL" },
      { id: 6, name: "Cacık", price: "250 TL" },
      { id: 7, name: "Cennet Ezmesi", price: "280 TL" },
      { id: 8, name: "Raw Rice", price: "280 TL" },
      { id: 9, name: "Cowpea", price: "280 TL" },
      { id: 10, name: "Sour Purslane", price: "280 TL" },
      { id: 11, name: "Artichoke", price: "300 TL" },
      { id: 12, name: "Plum Meze", price: "200 TL" },
      { id: 13, name: "Fava", price: "200 TL" },
      { id: 14, name: "Haydari", price: "200 TL" },
      { id: 15, name: "Roasted Red Pepper", price: "200 TL" },
      { id: 16, name: "Zucchini Girit", price: "200 TL" },
      { id: 17, name: "Zucchini Şahin", price: "200 TL" },
      { id: 18, name: "Sea Fennel", price: "200 TL" },
      { id: 19, name: "Köpoğlu", price: "300 TL" },
      { id: 20, name: "Dried Cowpea", price: "150 TL" },
      { id: 21, name: "Manco", price: "200 TL" },
      { id: 22, name: "Sour Mushroom", price: "200 TL" },
      { id: 23, name: "Beetroot", price: "200 TL" },
      { id: 24, name: "Orange Eggplant", price: "200 TL" },
      { id: 25, name: "Yogurt Eggplant", price: "200 TL" },
      { id: 26, name: "Zucchini", price: "price not available" },
      { id: 27, name: "Roasted Zucchini", price: "price not available" },
      { id: 28, name: "Red Pepper", price: "price not available" },
      { id: 29, name: "Dried", price: "price not available" },
      { id: 30, name: "Mushroom", price: "price not available" },
      { id: 31, name: "Cheese Melon", price: "400 TL" },
      { id: 32, name: "Cheese Plate", price: "350 TL" },
      { id: 33, name: "Pilaki", price: "200 TL" },
      { id: 34, name: "Arugula", price: "price not available" },
      { id: 35, name: "Saksuka", price: "200 TL" },
      { id: 36, name: "Yogurt Purslane", price: "200 TL" },
      { id: 37, name: "Şevketi Bostan", price: "200 TL" },
      { id: 38, name: "Topik", price: "200 TL" },
      { id: 39, name: "Turnip Greens", price: "200 TL" },
      { id: 40, name: "Green Cowpea", price: "200 TL" },
    ],
  },
  {
    id: 7,
    name: "Salads",
    items: [
      { id: 1, name: "Gavurdağ Spoon Salad", price: "400 TL - 450 TL" },
      { id: 2, name: "Shepherd's Salad", price: "350 TL - S. 200 TL" },
      { id: 3, name: "Arugula Salad with Cheese", price: "400 TL - 450 TL" },
      { id: 4, name: "Green Salad", price: "350 TL - S. 200 TL" },
      { id: 5, name: "Mixed Salad", price: "350 TL" },
      { id: 6, name: "Cheese Salad", price: "400 TL" },
      { id: 7, name: "Spoon Salad", price: "350 TL" },
    ],
  },
  {
    id: 4,
    name: "Hot Appetizers",
    items: [
      { id: 1, name: "Mushroom", price: "200 TL" },
      { id: 2, name: "Paçanga Böreği", price: "350 TL" },
      { id: 3, name: "Sigara Böreği", price: "280 TL" },
      { id: 4, name: "Fried Potatoes (Small)", price: "350 TL" },
      { id: 5, name: "Fried Potatoes (Double)", price: "400 TL" },
      { id: 6, name: "Chips", price: "300 TL" },
      { id: 7, name: "Chips (Double)", price: "350 TL" },
      { id: 8, name: "Hot Turnip Greens", price: "300 TL" },
      { id: 9, name: "Hot Eggplant", price: "300 TL" },
    ],
  },
  {
    id: 12,
    name: "Seafood",
    items: [
      { id: 1, name: "Octopus and Varieties", price: "850 TL - 950 TL" },
      { id: 2, name: "Shrimp and Varieties", price: "700 TL" },
      { id: 3, name: "Marinated Sea Bass", price: "550 TL" },
      { id: 4, name: "Sauced Anchovy", price: "500 TL" },
      { id: 5, name: "Fried / Grilled Calamari", price: "400 TL - 450 TL" },
      { id: 6, name: "Grilled / Casserole Octopus", price: "500 TL - 550 TL" },
      { id: 7, name: "Grilled / Fried / Casserole Shrimp", price: "750 TL - 800 TL - 850 TL" },
      { id: 8, name: "Sea Bass Chips", price: "900 TL" },
      { id: 9, name: "Ocean Delight", price: "500 TL" },
      { id: 10, name: "Sea Bream (producer unit)", price: "price not available" },
      { id: 11, name: "Sea Bream", price: "price not available" },
      { id: 12, name: "Sea Bass", price: "price not available" },
      { id: 13, name: "Red Mullet", price: "price not available" },
      { id: 14, name: "Lahos", price: "price not available" },
      { id: 15, name: "Dentex", price: "price not available" },
      { id: 16, name: "Red Sea Bream", price: "price not available" },
      { id: 17, name: "Amberjack", price: "price not available" },
    ],
  },
  {
    id: 5,
    name: "Main Courses",
    items: [
      { id: 1, name: "Grilled Meatballs", price: "600 TL" },
      { id: 2, name: "Grilled Chicken", price: "550 TL" },
      { id: 3, name: "Lamb Shish", price: "800 TL" },
      { id: 4, name: "Mixed Grill", price: "950 TL" },
      { id: 5, name: "Kavurma", price: "850 TL" },
      { id: 6, name: "Chicken Sauté", price: "750 TL / 1.350 TL" },
      { id: 7, name: "Meat Sauté", price: "950 TL / 1.800 TL" },
    ],
  },
  {
    id: 11,
    name: "Desserts",
    items: [
      { id: 1, name: "Quince Dessert", price: "300 TL" },
      { id: 2, name: "Pumpkin Dessert", price: "300 TL" },
      { id: 3, name: "Fig Dessert", price: "300 TL" },
      { id: 4, name: "Baked Halva", price: "450 TL" },
      { id: 5, name: "Katmer Dessert", price: "450 TL" },
      { id: 6, name: "Fruit Plate", price: "400 TL" },
      { id: 7, name: "Fruit Plate (double)", price: "550 TL" },
      { id: 8, name: "Honey Banana", price: "300 TL" },
      { id: 9, name: "Spoon Quince", price: "300 TL" },
    ],
  },
  {
    id: 6,
    name: "Drinks",
    items: [
      { id: 1, name: "Coke", price: "100 TL" },
      { id: 2, name: "Fanta", price: "100 TL" },
      { id: 3, name: "Gazoz", price: "100 TL" },
      { id: 4, name: "Ice Tea and varieties", price: "120 TL" },
      { id: 5, name: "Fruit Juices", price: "120 TL" },
      { id: 6, name: "Ayran", price: "80 TL" },
      { id: 7, name: "Soda", price: "80 TL" },
      { id: 8, name: "Lemon Soda", price: "100 TL" },
      { id: 9, name: "Turkish Coffee", price: "80 TL - 120 TL" },
      { id: 10, name: "Nescafe", price: "150 TL" },
      { id: 11, name: "Herbal Tea", price: "80 TL" },
      { id: 12, name: "Tea", price: "50 TL" },
      { id: 13, name: "Pot of Tea", price: "450 TL" },
      { id: 14, name: "Orange Juice", price: "180 TL" },
      { id: 15, name: "Şalgam (small)", price: "100 TL" },
      { id: 16, name: "Şalgam Bottle", price: "180 TL" },
      { id: 17, name: "Water", price: "75 TL" },
      { id: 18, name: "Beer and varieties", price: "250 TL" },
    ],
  },
  {
    id: 14, // Raki (New Category)
    name: "Raki",
    items: [
      { id: 1, name: "Efe Gold 20cl", price: "950 TL" },
      { id: 2, name: "Efe Gold 35cl", price: "1.200 TL" },
      { id: 3, name: "Efe Gold 50cl", price: "1.600 TL" },
      { id: 4, name: "Efe Gold 70cl", price: "2.150 TL" },
      { id: 5, name: "Efe Gold 100cl", price: "2.800 TL" },
      { id: 6, name: "Efe Yaş Üzüm 20cl", price: "700 TL" },
      { id: 7, name: "Efe Yaş Üzüm 35cl", price: "1.050 TL" },
      { id: 8, name: "Efe Yaş Üzüm 50cl", price: "1.450 TL" },
      { id: 9, name: "Efe Yaş Üzüm 70cl", price: "1.850 TL" },
      { id: 10, name: "Efe Yaş Üzüm 100cl", price: "2.500 TL" },
      { id: 11, name: "Efe Göbek Raki 20cl", price: "830 TL" },
      { id: 12, name: "Efe Göbek Raki 35cl", price: "1.200 TL" },
      { id: 13, name: "Efe Göbek Raki 50cl", price: "1.350 TL" },
      { id: 14, name: "Efe Göbek Raki 70cl", price: "2.350 TL" },
      { id: 15, name: "Efe Göbek Raki 100cl", price: "3.000 TL" },
      { id: 16, name: "Kara Efe Raki 20cl", price: "950 TL" },
      { id: 17, name: "Kara Efe Raki 35cl", price: "1.480 TL" },
      { id: 18, name: "Kara Efe Raki 70cl", price: "2.750 TL" },
      { id: 19, name: "Efe Gold Special Series 70cl", price: "price not available" },
      { id: 20, name: "Yeni Raki 20cl", price: "850 TL" },
      { id: 21, name: "Yeni Raki 35cl", price: "1.050 TL" },
      { id: 22, name: "Yeni Raki 50cl", price: "1.400 TL" },
      { id: 23, name: "Yeni Raki 70cl", price: "1.800 TL" },
      { id: 24, name: "Yeni Raki 100cl", price: "2.400 TL" },
      { id: 25, name: "Ala Raki 20cl", price: "840 TL" },
      { id: 26, name: "Ala Raki 35cl", price: "1.450 TL" },
      { id: 27, name: "Ala Raki 70cl", price: "2.600 TL" },
      { id: 28, name: "Y.R New Series 20cl", price: "900 TL" },
      { id: 29, name: "Y.R New Series 35cl", price: "1.150 TL" },
      { id: 30, name: "Y.R New Series 70cl", price: "2.000 TL" },
      { id: 31, name: "Tekirdağ Raki 20cl", price: "800 TL" },
      { id: 32, name: "Tekirdağ Raki 35cl", price: "1.400 TL" },
      { id: 33, name: "Tekirdağ Raki 50cl", price: "1.550 TL" },
      { id: 34, name: "Tekirdağ Raki 70cl", price: "2.000 TL" },
      { id: 35, name: "Tekirdağ Gold 20cl", price: "800 TL" },
      { id: 36, name: "Tekirdağ Gold 35cl", price: "1.200 TL" },
      { id: 37, name: "Tekirdağ Gold 50cl", price: "1.700 TL" },
      { id: 38, name: "Tekirdağ Gold 70cl", price: "2.200 TL" },
      { id: 39, name: "Tekirdağ Gold 100cl", price: "2.900 TL" },
      { id: 40, name: "Raki (T)", price: "350 TL" },
      { id: 41, name: "Raki (D)", price: "450 TL" },
    ],
  },
  {
    id: 15, // Wines (New Category)
    name: "Wines",
    items: [
      { id: 1, name: "V.Doluca (D)", price: "450 TL" },
      { id: 2, name: "V.Doluca 35cl", price: "350 TL" },
      { id: 3, name: "V.Doluca 70cl", price: "1.800 TL" },
      { id: 4, name: "Villa D. Neo 70cl", price: "price not available" },
      { id: 5, name: "Villa D. Rose 70cl", price: "price not available" },
      { id: 6, name: "Verano 70cl", price: "price not available" },
      { id: 7, name: "Antik 70cl", price: "price not available" },
      { id: 8, name: "Alçtepe Kirte 70cl", price: "price not available" },
      { id: 9, name: "Çankaya 35cl", price: "price not available" },
      { id: 10, name: "Çankaya 70cl", price: "price not available" },
      { id: 11, name: "DLC Boğazkere 70cl", price: "price not available" },
      { id: 12, name: "DLC Cab. Sauvignon Merlot 70cl", price: "price not available" },
      { id: 13, name: "DLC Grenache 70cl", price: "price not available" },
      { id: 14, name: "DLC Kalecik Karası 70cl", price: "price not available" },
      { id: 15, name: "DLC Moskado (Dömişek) 70cl", price: "price not available" },
      { id: 16, name: "DLC Narince 70cl", price: "price not available" },
      { id: 17, name: "DLC Öküzgözü 70cl", price: "price not available" },
      { id: 18, name: "DLC Ply 70cl", price: "price not available" },
      { id: 19, name: "DLC Shiraz 70cl", price: "price not available" },
      { id: 20, name: "DLC Sauvignon Blanc 70cl", price: "price not available" },
      { id: 21, name: "DLC Sultaniiye Emir 70cl", price: "price not available" },
      { id: 22, name: "Kav Narince 70cl", price: "price not available" },
      { id: 23, name: "Terra Öküzgözü Boğazkere 70cl", price: "price not available" },
      { id: 24, name: "Küp Beş Bir Yerden White 70cl", price: "price not available" },
      { id: 25, name: "Küp Beş Bir Yerden Red 70cl", price: "price not available" },
      { id: 26, name: "Küp Epic Chardonnay 70cl", price: "price not available" },
      { id: 27, name: "Küp Epic Merlot 70cl", price: "price not available" },
      { id: 28, name: "Küp Thia Blush 70cl", price: "price not available" },
      { id: 29, name: "Küp Thia Cab. Sav. 70cl", price: "price not available" },
      { id: 30, name: "Küp Thia Chardonnay 70cl", price: "price not available" },
      { id: 31, name: "Küp Thia Merlot 70cl", price: "price not available" },
      { id: 32, name: "Küp Sav Blanc 70cl", price: "price not available" },
      { id: 33, name: "Leona Blush 70cl", price: "price not available" },
      { id: 34, name: "Leona Buble 70cl", price: "price not available" },
      { id: 35, name: "Leona Narince 70cl", price: "price not available" },
      { id: 36, name: "Leona Shiraz 70cl", price: "price not available" },
      { id: 37, name: "Sarafin Cab. Sauvignon 35cl", price: "price not available" },
      { id: 38, name: "Sarafin Cab. Sauvignon 70cl", price: "price not available" },
      { id: 39, name: "Sarafin Sauvignon Blanc 70cl", price: "price not available" },
      { id: 40, name: "Sarafin Meritage 70cl", price: "price not available" },
      { id: 41, name: "Sarafin Rose 70cl", price: "price not available" },
      { id: 42, name: "Selection 70cl", price: "price not available" },
      { id: 43, name: "Signum White 70cl", price: "price not available" },
      { id: 44, name: "Signum Rose 70cl", price: "price not available" },
      { id: 45, name: "Signum Red 70cl", price: "price not available" },
    ],
  },
]

const deMenuData: MenuCategoryData[] = [
  {
    id: 2,
    name: "Frühstück",
    items: [
      {
        id: 1,
        name: "Ausgiebiges Frühstück pro Person",
        price: "650 TL",
        description:
          "Kalte Platte, schwarze und rote Oliven, 4 Käsesorten, hausgemachte Marmelade, Haselnusscreme, Honig, Sahne, Sigara Böreği, Spiegelei, Teekanne.",
      },
      { id: 2, name: "Omelett", price: "300 TL" },
      { id: 3, name: "Omelett mit Sucuk", price: "350 TL" },
      { id: 4, name: "Gemischtes Omelett", price: "350 TL" },
      { id: 5, name: "Käse-Omelett", price: "300 TL" },
      { id: 6, name: "Eier mit Käse", price: "300 TL" },
      { id: 7, name: "Spiegelei mit Käse", price: "280 TL" },
      { id: 8, name: "Spiegelei (für 2 Personen)", price: "300 TL" },
      { id: 9, name: "Spiegelei (für 4 Personen)", price: "350 TL" },
      { id: 10, name: "Eier mit Kartoffeln", price: "300 TL" },
      { id: 11, name: "Sucuk (für 2 Personen)", price: "300 TL" },
      { id: 12, name: "Sucuk (für 4 Personen)", price: "400 TL" },
      { id: 13, name: "Sucuk mit Eiern (für 2 Personen)", price: "350 TL" },
      { id: 14, name: "Sucuk mit Eiern (für 4 Personen)", price: "450 TL" },
      { id: 15, name: "Gekochtes Ei", price: "50 TL" },
      { id: 16, name: "Pommes", price: "400 TL" },
      { id: 17, name: "Menemen (für 2 Personen)", price: "300 TL" },
      { id: 18, name: "Menemen (für 4 Personen)", price: "350 TL" },
      { id: 19, name: "Sigara Böreği", price: "280 TL" },
    ],
  },
  {
    id: 3,
    name: "Kalte Vorspeisen",
    items: [
      { id: 1, name: "Scharfes Ezme", price: "290 TL" },
      { id: 2, name: "Atom", price: "290 TL" },
      { id: 3, name: "Paprika Tarator", price: "290 TL" },
      { id: 4, name: "Borani", price: "280 TL" },
      { id: 5, name: "Brokkoli", price: "290 TL" },
      { id: 6, name: "Cacık", price: "250 TL" },
      { id: 7, name: "Cennet Ezmesi", price: "280 TL" },
      { id: 8, name: "Roher Reis", price: "280 TL" },
      { id: 9, name: "Augenbohne", price: "280 TL" },
      { id: 10, name: "Saurer Portulak", price: "280 TL" },
      { id: 11, name: "Artischocke", price: "300 TL" },
      { id: 12, name: "Pflaumen-Meze", price: "200 TL" },
      { id: 13, name: "Fava", price: "200 TL" },
      { id: 14, name: "Haydari", price: "200 TL" },
      { id: 15, name: "Geröstete rote Paprika", price: "200 TL" },
      { id: 16, name: "Zucchini Girit", price: "200 TL" },
      { id: 17, name: "Zucchini Şahin", price: "200 TL" },
      { id: 18, name: "Meerfenchel", price: "200 TL" },
      { id: 19, name: "Köpoğlu", price: "300 TL" },
      { id: 20, name: "Getrocknete Augenbohne", price: "150 TL" },
      { id: 21, name: "Manco", price: "200 TL" },
      { id: 22, name: "Saure Pilze", price: "200 TL" },
      { id: 23, name: "Rote Bete", price: "200 TL" },
      { id: 24, name: "Orangen-Aubergine", price: "200 TL" },
      { id: 25, name: "Joghurt-Aubergine", price: "200 TL" },
      { id: 26, name: "Zucchini", price: "Preis nicht verfügbar" },
      { id: 27, name: "Geröstete Zucchini", price: "Preis nicht verfügbar" },
      { id: 28, name: "Rote Paprika", price: "Preis nicht verfügbar" },
      { id: 29, name: "Getrocknet", price: "Preis nicht verfügbar" },
      { id: 30, name: "Pilz", price: "Preis nicht verfügbar" },
      { id: 31, name: "Käse-Melone", price: "400 TL" },
      { id: 32, name: "Käseplatte", price: "350 TL" },
      { id: 33, name: "Pilaki", price: "200 TL" },
      { id: 34, name: "Rucola", price: "Preis nicht verfügbar" },
      { id: 35, name: "Saksuka", price: "200 TL" },
      { id: 36, name: "Joghurt-Portulak", price: "200 TL" },
      { id: 37, name: "Şevketi Bostan", price: "200 TL" },
      { id: 38, name: "Topik", price: "200 TL" },
      { id: 39, name: "Rübenkraut", price: "200 TL" },
      { id: 40, name: "Grüne Augenbohne", price: "200 TL" },
    ],
  },
  {
    id: 7,
    name: "Salate",
    items: [
      { id: 1, name: "Gavurdağ Löffelsalat", price: "400 TL - 450 TL" },
      { id: 2, name: "Hirtensalat", price: "350 TL - K. 200 TL" },
      { id: 3, name: "Rucola-Salat mit Käse", price: "400 TL - 450 TL" },
      { id: 4, name: "Grüner Salat", price: "350 TL - K. 200 TL" },
      { id: 5, name: "Gemischter Salat", price: "350 TL" },
      { id: 6, name: "Käsesalat", price: "400 TL" },
      { id: 7, name: "Löffelsalat", price: "350 TL" },
    ],
  },
  {
    id: 4,
    name: "Warme Vorspeisen",
    items: [
      { id: 1, name: "Pilz", price: "200 TL" },
      { id: 2, name: "Paçanga Böreği", price: "350 TL" },
      { id: 3, name: "Sigara Böreği", price: "280 TL" },
      { id: 4, name: "Pommes (Klein)", price: "350 TL" },
      { id: 5, name: "Pommes (Doppelt)", price: "400 TL" },
      { id: 6, name: "Chips", price: "300 TL" },
      { id: 7, name: "Chips (Doppelt)", price: "350 TL" },
      { id: 8, name: "Warmer Rübenkraut", price: "300 TL" },
      { id: 9, name: "Warme Aubergine", price: "300 TL" },
    ],
  },
  {
    id: 12,
    name: "Meeresfrüchte",
    items: [
      { id: 1, name: "Oktopus und Variationen", price: "850 TL - 950 TL" },
      { id: 2, name: "Garnelen und Variationen", price: "700 TL" },
      { id: 3, name: "Marinierter Wolfsbarsch", price: "550 TL" },
      { id: 4, name: "Sardellen mit Sauce", price: "500 TL" },
      { id: 5, name: "Gebratener / Gegrillter Tintenfisch", price: "400 TL - 450 TL" },
      { id: 6, name: "Gegrillter / Auflauf-Oktopus", price: "500 TL - 550 TL" },
      { id: 7, name: "Gegrillte / Gebratene / Auflauf-Garnelen", price: "750 TL - 800 TL - 850 TL" },
      { id: 8, name: "Wolfsbarsch-Chips", price: "900 TL" },
      { id: 9, name: "Ozean-Delikatesse", price: "500 TL" },
      { id: 10, name: "Dorade (Produzenteneinheit)", price: "Preis nicht verfügbar" },
      { id: 11, name: "Dorade", price: "Preis nicht verfügbar" },
      { id: 12, name: "Wolfsbarsch", price: "Preis nicht verfügbar" },
      { id: 13, name: "Meerbarbe", price: "Preis nicht verfügbar" },
      { id: 14, name: "Lahos", price: "Preis nicht verfügbar" },
      { id: 15, name: "Zahnbrasse", price: "Preis nicht verfügbar" },
      { id: 16, name: "Rotbrasse", price: "Preis nicht verfügbar" },
      { id: 17, name: "Bernsteinmakrele", price: "Preis nicht verfügbar" },
    ],
  },
  {
    id: 5,
    name: "Hauptgerichte",
    items: [
      { id: 1, name: "Gegrillte Frikadellen", price: "600 TL" },
      { id: 2, name: "Gegrilltes Hähnchen", price: "550 TL" },
      { id: 3, name: "Lammspieß", price: "800 TL" },
      { id: 4, name: "Gemischter Grillteller", price: "950 TL" },
      { id: 5, name: "Kavurma", price: "850 TL" },
      { id: 6, name: "Hähnchen-Sauté", price: "750 TL / 1.350 TL" },
      { id: 7, name: "Fleisch-Sauté", price: "950 TL / 1.800 TL" },
    ],
  },
  {
    id: 11,
    name: "Desserts",
    items: [
      { id: 1, name: "Quitten-Dessert", price: "300 TL" },
      { id: 2, name: "Kürbis-Dessert", price: "300 TL" },
      { id: 3, name: "Feigen-Dessert", price: "300 TL" },
      { id: 4, name: "Ofen-Halva", price: "450 TL" },
      { id: 5, name: "Katmer-Dessert", price: "450 TL" },
      { id: 6, name: "Obstteller", price: "400 TL" },
      { id: 7, name: "Obstteller (doppelt)", price: "550 TL" },
      { id: 8, name: "Honig-Banane", price: "300 TL" },
      { id: 9, name: "Löffel-Quitte", price: "300 TL" },
    ],
  },
  {
    id: 6,
    name: "Getränke",
    items: [
      { id: 1, name: "Cola", price: "100 TL" },
      { id: 2, name: "Fanta", price: "100 TL" },
      { id: 3, name: "Gazoz", price: "100 TL" },
      { id: 4, name: "Eistee und Sorten", price: "120 TL" },
      { id: 5, name: "Fruchtsäfte", price: "120 TL" },
      { id: 6, name: "Ayran", price: "80 TL" },
      { id: 7, name: "Soda", price: "80 TL" },
      { id: 8, name: "Zitronen-Soda", price: "100 TL" },
      { id: 9, name: "Türkischer Kaffee", price: "80 TL - 120 TL" },
      { id: 10, name: "Nescafe", price: "150 TL" },
      { id: 11, name: "Kräutertee", price: "80 TL" },
      { id: 12, name: "Tee", price: "50 TL" },
      { id: 13, name: "Teekanne", price: "450 TL" },
      { id: 14, name: "Orangensaft", price: "180 TL" },
      { id: 15, name: "Şalgam (klein)", price: "100 TL" },
      { id: 16, name: "Şalgam Flasche", price: "180 TL" },
      { id: 17, name: "Wasser", price: "75 TL" },
      { id: 18, name: "Bier und Sorten", price: "250 TL" },
    ],
  },
  {
    id: 14, // Rakı (Neue Kategorie)
    name: "Rakı",
    items: [
      { id: 1, name: "Efe Gold 20cl", price: "950 TL" },
      { id: 2, name: "Efe Gold 35cl", price: "1.200 TL" },
      { id: 3, name: "Efe Gold 50cl", price: "1.600 TL" },
      { id: 4, name: "Efe Gold 70cl", price: "2.150 TL" },
      { id: 5, name: "Efe Gold 100cl", price: "2.800 TL" },
      { id: 6, name: "Efe Yaş Üzüm 20cl", price: "700 TL" },
      { id: 7, name: "Efe Yaş Üzüm 35cl", price: "1.050 TL" },
      { id: 8, name: "Efe Yaş Üzüm 50cl", price: "1.450 TL" },
      { id: 9, name: "Efe Yaş Üzüm 70cl", price: "1.850 TL" },
      { id: 10, name: "Efe Yaş Üzüm 100cl", price: "2.500 TL" },
      { id: 11, name: "Efe Göbek Rakı 20cl", price: "830 TL" },
      { id: 12, name: "Efe Göbek Rakı 35cl", price: "1.200 TL" },
      { id: 13, name: "Efe Göbek Rakı 50cl", price: "1.350 TL" },
      { id: 14, name: "Efe Göbek Rakı 70cl", price: "2.350 TL" },
      { id: 15, name: "Efe Göbek Rakı 100cl", price: "3.000 TL" },
      { id: 16, name: "Kara Efe Rakı 20cl", price: "950 TL" },
      { id: 17, name: "Kara Efe Rakı 35cl", price: "1.480 TL" },
      { id: 18, name: "Kara Efe Rakı 70cl", price: "2.750 TL" },
      { id: 19, name: "Efe Gold Spezialserie 70cl", price: "Preis nicht verfügbar" },
      { id: 20, name: "Yeni Rakı 20cl", price: "850 TL" },
      { id: 21, name: "Yeni Rakı 35cl", price: "1.050 TL" },
      { id: 22, name: "Yeni Rakı 50cl", price: "1.400 TL" },
      { id: 23, name: "Yeni Rakı 70cl", price: "1.800 TL" },
      { id: 24, name: "Yeni Rakı 100cl", price: "2.400 TL" },
      { id: 25, name: "Ala Rakı 20cl", price: "840 TL" },
      { id: 26, name: "Ala Rakı 35cl", price: "1.450 TL" },
      { id: 27, name: "Ala Rakı 70cl", price: "2.600 TL" },
      { id: 28, name: "Y.R Neue Serie 20cl", price: "900 TL" },
      { id: 29, name: "Y.R Neue Serie 35cl", price: "1.150 TL" },
      { id: 30, name: "Y.R Neue Serie 70cl", price: "2.000 TL" },
      { id: 31, name: "Tekirdağ Rakı 20cl", price: "800 TL" },
      { id: 32, name: "Tekirdağ Rakı 35cl", price: "1.400 TL" },
      { id: 33, name: "Tekirdağ Rakı 50cl", price: "1.550 TL" },
      { id: 34, name: "Tekirdağ Rakı 70cl", price: "2.000 TL" },
      { id: 35, name: "Tekirdağ Gold 20cl", price: "800 TL" },
      { id: 36, name: "Tekirdağ Gold 35cl", price: "1.200 TL" },
      { id: 37, name: "Tekirdağ Gold 50cl", price: "1.700 TL" },
      { id: 38, name: "Tekirdağ Gold 70cl", price: "2.200 TL" },
      { id: 39, name: "Tekirdağ Gold 100cl", price: "2.900 TL" },
      { id: 40, name: "Rakı (T)", price: "350 TL" },
      { id: 41, name: "Rakı (D)", price: "450 TL" },
    ],
  },
  {
    id: 15, // Weine (Neue Kategorie)
    name: "Weine",
    items: [
      { id: 1, name: "V.Doluca (D)", price: "450 TL" },
      { id: 2, name: "V.Doluca 35cl", price: "350 TL" },
      { id: 3, name: "V.Doluca 70cl", price: "1.800 TL" },
      { id: 4, name: "Villa D. Neo 70cl", price: "Preis nicht verfügbar" },
      { id: 5, name: "Villa D. Rosé 70cl", price: "Preis nicht verfügbar" },
      { id: 6, name: "Verano 70cl", price: "Preis nicht verfügbar" },
      { id: 7, name: "Antik 70cl", price: "Preis nicht verfügbar" },
      { id: 8, name: "Alçtepe Kirte 70cl", price: "Preis nicht verfügbar" },
      { id: 9, name: "Çankaya 35cl", price: "Preis nicht verfügbar" },
      { id: 10, name: "Çankaya 70cl", price: "Preis nicht verfügbar" },
      { id: 11, name: "DLC Boğazkere 70cl", price: "Preis nicht verfügbar" },
      { id: 12, name: "DLC Cab. Sauvignon Merlot 70cl", price: "Preis nicht verfügbar" },
      { id: 13, name: "DLC Grenache 70cl", price: "Preis nicht verfügbar" },
      { id: 14, name: "DLC Kalecik Karası 70cl", price: "Preis nicht verfügbar" },
      { id: 15, name: "DLC Moskado (Dömişek) 70cl", price: "Preis nicht verfügbar" },
      { id: 16, name: "DLC Narince 70cl", price: "Preis nicht verfügbar" },
      { id: 17, name: "DLC Öküzgözü 70cl", price: "Preis nicht verfügbar" },
      { id: 18, name: "DLC Ply 70cl", price: "Preis nicht verfügbar" },
      { id: 19, name: "DLC Shiraz 70cl", price: "Preis nicht verfügbar" },
      { id: 20, name: "DLC Sauvignon Blanc 70cl", price: "Preis nicht verfügbar" },
      { id: 21, name: "DLC Sultaniiye Emir 70cl", price: "Preis nicht verfügbar" },
      { id: 22, name: "Kav Narince 70cl", price: "Preis nicht verfügbar" },
      { id: 23, name: "Terra Öküzgözü Boğazkere 70cl", price: "Preis nicht verfügbar" },
      { id: 24, name: "Küp Beş Bir Yerden Weiß 70cl", price: "Preis nicht verfügbar" },
      { id: 25, name: "Küp Beş Bir Yerden Rot 70cl", price: "Preis nicht verfügbar" },
      { id: 26, name: "Küp Epic Chardonnay 70cl", price: "Preis nicht verfügbar" },
      { id: 27, name: "Küp Epic Merlot 70cl", price: "Preis nicht verfügbar" },
      { id: 28, name: "Küp Thia Blush 70cl", price: "Preis nicht verfügbar" },
      { id: 29, name: "Küp Thia Cab. Sav. 70cl", price: "Preis nicht verfügbar" },
      { id: 30, name: "Küp Thia Chardonnay 70cl", price: "Preis nicht verfügbar" },
      { id: 31, name: "Küp Thia Merlot 70cl", price: "Preis nicht verfügbar" },
      { id: 32, name: "Küp Sav Blanc 70cl", price: "Preis nicht verfügbar" },
      { id: 33, name: "Leona Blush 70cl", price: "Preis nicht verfügbar" },
      { id: 34, name: "Leona Buble 70cl", price: "Preis nicht verfügbar" },
      { id: 35, name: "Leona Narince 70cl", price: "Preis nicht verfügbar" },
      { id: 36, name: "Leona Shiraz 70cl", price: "Preis nicht verfügbar" },
      { id: 37, name: "Sarafin Cab. Sauvignon 35cl", price: "Preis nicht verfügbar" },
      { id: 38, name: "Sarafin Cab. Sauvignon 70cl", price: "Preis nicht verfügbar" },
      { id: 39, name: "Sarafin Sauvignon Blanc 70cl", price: "Preis nicht verfügbar" },
      { id: 40, name: "Sarafin Meritage 70cl", price: "Preis nicht verfügbar" },
      { id: 41, name: "Sarafin Rosé 70cl", price: "Preis nicht verfügbar" },
      { id: 42, name: "Selection 70cl", price: "Preis nicht verfügbar" },
      { id: 43, name: "Signum Weiß 70cl", price: "Preis nicht verfügbar" },
      { id: 44, name: "Signum Rosé 70cl", price: "Preis nicht verfügbar" },
      { id: 45, name: "Signum Rot 70cl", price: "Preis nicht verfügbar" },
    ],
  },
]

export function getMenuData(locale: string): MenuCategoryData[] {
  switch (locale) {
    case "tr":
      return trMenuData
    case "en":
      return enMenuData
    case "de":
      return deMenuData
    default:
      return trMenuData
  }
}
